
-- Query 1: Find the most visited doctor based on total appointments
SELECT d.doctor_id,d.first_name,d.specialization,COUNT(a.doctor_id) AS total_visits
FROM doctors d
JOIN appointments a ON d.doctor_id=a.doctor_id
GROUP BY d.doctor_id,d.first_name,d.specialization
ORDER BY total_visits DESC;


-- Query 2: Calculate total billing amount spent by each patient
SELECT p.patient_id,p.first_name,SUM(b.amount) AS total_amount
FROM patients p
JOIN billing b ON p.patient_id=b.patient_id
GROUP BY p.patient_id,p.first_name
ORDER BY total_amount DESC;


-- Query 3: Find the highest earning doctor based on total treatment cost
SELECT d.doctor_id,d.first_name,SUM(t.cost) AS total_earning
FROM doctors d
JOIN appointments a ON a.doctor_id=d.doctor_id
JOIN treatments t ON a.appointment_id=t.appointment_id
GROUP BY d.doctor_id,d.first_name
ORDER BY total_earning DESC;


-- Query 4: Find patients who paid more than the average billing amount
SELECT p.patient_id,p.first_name,b.amount 
FROM patients p
JOIN billing b ON b.patient_id=p.patient_id
WHERE b.amount > (SELECT AVG(amount) FROM billing);


-- Query 5: Calculate monthly revenue generated from billing records
SELECT TO_CHAR(bill_date,'YYYY-MM') as billing_month,SUM(amount) AS monthly_revenue
FROM billing
GROUP BY billing_month
ORDER BY billing_month;


-- Query 6: Find top earning doctor in each hospital branch using window function
SELECT * FROM (
SELECT d.doctor_id,d.first_name,d.hospital_branch,SUM(b.amount) AS revenue,
RANK() OVER(PARTITION BY d.hospital_branch ORDER BY SUM(b.amount) DESC) AS rnk
FROM doctors d
JOIN appointments a ON a.doctor_id=d.doctor_id
JOIN treatments t ON t.appointment_id=a.appointment_id
JOIN billing b ON b.treatment_id=t.treatment_id
GROUP BY d.doctor_id,d.first_name,d.hospital_branch
)
WHERE rnk = 1;


-- Query 7: Find patients who have more than 2 appointments
SELECT p.patient_id,p.first_name,COUNT(a.appointment_id) AS Appointments
FROM patients p
JOIN appointments a ON p.patient_id=a.patient_id
GROUP BY p.patient_id,p.first_name
HAVING COUNT(a.appointment_id) > 2
ORDER BY Appointments;


-- Query 8: Find the latest appointment for each patient
SELECT  * FROM (
SELECT p.patient_id,p.first_name,a.appointment_date AS latest_appointment,
ROW_NUMBER() OVER(PARTITION BY a.patient_id ORDER BY a.appointment_date DESC) AS RNK
FROM patients p
JOIN appointments a ON p.patient_id=a.patient_id
) 
WHERE RNK = 1;


-- Query 9: Calculate total number of treatments handled by each doctor
SELECT d.doctor_id,d.first_name,COUNT(t.treatment_id) AS total_treatments
FROM doctors d
JOIN appointments a ON d.doctor_id = a.doctor_id
JOIN treatments t ON a.appointment_id = t.appointment_id
GROUP BY d.doctor_id,d.first_name
ORDER BY total_treatments DESC;


-- Query 10: Calculate total spending per patient using CTE
WITH spending AS (
SELECT patient_id,SUM(amount) AS Total_spend
FROM billing
GROUP BY patient_id
)

SELECT s.*,p.first_name 
FROM spending s
JOIN patients p ON p.patient_id=s.patient_id
ORDER BY patient_id;


-- Query 11: Find top 5 patients based on total billing amount
SELECT p.patient_id,p.first_name,SUM(b.amount) AS Total_spend
FROM patients p
JOIN billing b ON p.patient_id=b.patient_id
GROUP BY p.patient_id,p.first_name
ORDER BY Total_spend DESC LIMIT 5;


-- Query 12: Calculate total revenue generated by each hospital branch
SELECT d.hospital_branch, SUM(b.amount) AS Revenue
FROM doctors d
JOIN appointments a ON a.doctor_id=d.doctor_id
JOIN treatments t ON t.appointment_id=a.appointment_id
JOIN billing b ON b.treatment_id=t.treatment_id
GROUP BY d.hospital_branch
ORDER BY Revenue DESC;
